### ISSUE TITLE
Update Promise implementation to match new spec

### ISSUE THREAD

**Issue by cscott** [paulmillr/es6-shim#239]
@domenic has updated the `Promise` spec: https://github.com/domenic/promises-unwrapping/issues/99#issuecomment-39188107

I do not believe there are any functional changes, so this isn't a critical update.  But I should update our implementation to better match the spec to make it more obviously correct (and to simplify, and to check @domenic's work!).

**Comment by ljharb** [comment]
Fixed with 9542dda06c1812cefd14b5c6101a9f35ec1f2eda / #345
