### ISSUE TITLE
"chalk" adds non-function String#bold; breaks v0.25.1.

### ISSUE THREAD

**Issue by rwaldron** [paulmillr/es6-shim#315]
https://github.com/paulmillr/es6-shim/commit/a0e0544eefd6b42b5e514584a4413033ed1c3219#commitcomment-9801840

**Comment by ljharb** [comment]
Thanks for the report! This definitely isn't meant to break. Can you provide some more info about what's breaking and what environment it's breaking on?

**Comment by ljharb** [comment]
My confusion here is that every key in https://github.com/paulmillr/es6-shim/commit/a0e0544eefd6b42b5e514584a4413033ed1c3219#diff-fbdfeb59ea7599799df83561186da7dfR2522 is installed on `String.prototype` in https://github.com/paulmillr/es6-shim/commit/a0e0544eefd6b42b5e514584a4413033ed1c3219#diff-fbdfeb59ea7599799df83561186da7dfR2521 - I wonder if arduinos have an Object.keys bug?

**Comment by ljharb** [comment]
OK, I think I figured it out. The `npm` module `chalk` unfortunately modifies `String.prototype` - which is not only a bad idea (for things that aren't shims), but also, it means that `es6-shim` is being required in after `chalk` is required, and usually the shim should be run first.

That said, I can certainly work around this.

**Comment by ljharb** [comment]
Fix will be published shortly - that said, I'd avoid using "chalk" if at all possible in the future.

**Comment by olizilla** [comment]
for future archeologists, it's colors.js that's all up in the String.prototype, causing trouble, not chalk.

**Comment by ljharb** [comment]
@olizilla thanks, i've updated all my comments and the issue description
