### ISSUE TITLE
Map/Set error message is misleading

### ISSUE THREAD

**Issue by webbedspace** [paulmillr/es6-shim#321]
The error message for calling `Map` without a function is `'Map does not accept arguments when called as a function'`, but it should really read `'Map cannot be called as a function'`. Ditto Set.

(In the current spec, Map will [always throw](https://people.mozilla.org/~jorendorff/es6-draft.html#sec-map-iterable) without the `new` keyword, regardless of arguments.)

**Comment by ljharb** [comment]
Thanks, these messages are what current engines that implemented `Map`/`Set` threw, but now `io.js`'s v8 implements them correctly, I'll update them to use their messages.

**Comment by webbedspace** [comment]
In addition, you should update it so that `Map.call(new Map())` is an error (ditto Set).

**Comment by ljharb** [comment]
I'm not sure if that's possible - `NewTarget` can't be shimmed or detected.
