### ISSUE TITLE
Array#slice bug

### ISSUE THREAD

**Issue by zloirock** [paulmillr/es6-shim#322]
About https://github.com/paulmillr/es6-shim/commit/bdd9804ddede0515b34646959d409c3c7a259e61 / https://github.com/kangax/compat-table/issues/453

By spec, [ArraySpeciesCreate](http://people.mozilla.org/~jorendorff/es6-draft.html#sec-arrayspeciescreate) shoud create instance `arrayLike.constructor` / `arrayLike.constructor[@@spicies]` only if `arrayLike` is array, see steps 4-7.

Current implementation different from spec and breaks old code - for example, `[].slice.call(document.getElementsByTagName('div'))` throws error.

**Comment by ljharb** [comment]
Unpublished `v0.27.0` from `npm` pending this issue.

**Comment by ljharb** [comment]
After rereading the spec algorithm, I think that perhaps this isn't shimmable. I'm going to revert this for now and revisit it in the future.
