### ISSUE TITLE
Can't work with webcomponents.js(@version 0.5.5) 

### ISSUE THREAD

**Issue by reutopiaer** [paulmillr/es6-shim#324]
es6-shim.js:29903 Uncaught RangeError: Maximum call stack size exceeded

    <!doctype html>
    <html>
    <head>
         <title></title>
        <script src="/quickstart/dist/es6-shim.js"></script>
        <script src="/bower_components/webcomponents.js/webcomponents.js"></script>
    </head>
    <body>
    </body>
    </html>

**Comment by ljharb** [comment]
I'm not sure what "webcomponents" is - can you provide more detail? Specifically, which function is hitting a recursion limit, and what the github repo (and npm package name) is for this?

**Comment by reutopiaer** [comment]
@ljharb   A suite of polyfills supporting the HTML Web Components specs  https://github.com/webcomponents/webcomponentsjs 
http://webcomponents.org/polyfills/

I want use es6-shim with polymerjs

**Comment by ljharb** [comment]
So which function is hitting a recursion limit? There's not 29,903 lines in `es6-shim.js` :-)

**Comment by reutopiaer** [comment]
I‘m very Sorry!   I have a huge mistake. 
I just find that my es6-shim.js is download from:  https://github.com/angular/quickstart/blob/master/dist/es6-shim.js
