### ISSUE TITLE
performance of `Math.hypot`

### ISSUE THREAD

**Issue by Yaffle** [paulmillr/es6-shim#346]
http://jsperf.com/math-hypot/8

**Comment by ljharb** [comment]
Thanks for the jsperf. The browserscope results seem to be erroring out for me - do you have a screenshot of them?

**Comment by Yaffle** [comment]
> The browserscope results seem to be erroring out for me

for me too

**Comment by ljharb** [comment]
Either way, our implementation is super slow, and `Math.hypotX` seems to be the fastest, it passes all tests, and it's not as unreadable as some of the others - I'll update to use it, thanks.

**Comment by Yaffle** [comment]
fine
