### ISSUE TITLE
window.Symbol is undefined in IE 11

### ISSUE THREAD

**Issue by clcrutch** [paulmillr/es6-shim#356]
AngularJS2 attempts to call window.Symbol and fails.

I was able to correct the issue with this:

    if (typeof(globals.Symbol) === 'undefined') {
        globals.Symbol = Symbol;
    }

![image](https://cloud.githubusercontent.com/assets/2128090/9013422/ad54964c-3770-11e5-95b7-ff4a9adc67f5.png)

**Comment by ljharb** [comment]
If Angular 2 depends on Symbols - which are *not* fully shimmable in any browser that doesn't ship with them - then it simply won't work in a browser that doesn't (like IE 11, and many other versions of browsers).

In no way would it be acceptable for `es6-shim` to assign an empty object to the global `Symbol` property just to fix an incompatibility in a random library.
