### ISSUE TITLE
Object.keys() fails in Node.js v0.12.7

### ISSUE THREAD

**Issue by cristian-smocot** [paulmillr/es6-shim#357]
`Object.keys()` spits: `TypeError: undefined is not a function`
Version: __0.33.0__
Sample test code:
```
  var keys = {a:1, b:2, c:3}.keys();
```

**Comment by mathiasbynens** [comment]
This report is invalid.

It’s `Object.keys`, not `Object.prototype.keys`.

**Comment by cristian-smocot** [comment]
Sorry!
My mistake. I realize now I read the documentation badly,
