### ISSUE TITLE
Silence Chrome webkitIndexedDB warning when es6-shim loads?

### ISSUE THREAD

**Issue by mikemaccana** [paulmillr/es6-shim#362]
> blacklistedKeys.indexOf(k)

Throws up this warning when looking for webkitIndexedDB.

> 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

It's obviously not a real error, and there's nothing wrong with es6-shim, because it's checking for blacklistedKeys. But Is there any way we can silence it?

**Comment by mikemaccana** [comment]
This also applies to:

> 'webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.

**Comment by ljharb** [comment]
Thanks for the report! This is actually an https://github.com/es-shims/es5-shim issue, can you file it there?

**Comment by ljharb** [comment]
(also, in the latest `es5-shim`, this may have been resolved already - it's not doing an `indexOf` anymore, it's doing an object lookup to a local cache)

**Comment by mikemaccana** [comment]
Thanks for the quick reply @ljharb! Since it's fixed in es5-shim, maybe it's worth bumping the version of es5-shim that es6-shim requires?
