### ISSUE TITLE
Remove @@species from Promise.all/Promise.race

### ISSUE THREAD

**Issue by ljharb** [paulmillr/es6-shim#374]
Per https://github.com/tc39/ecma262/issues/151, `Promise.all` and `Promise.race` no longer respect `Symbol.species`.

**Comment by ljharb** [comment]
Relates to #345 (I think)

**Comment by cscott** [comment]
Hm, first I'm hearing of it.  I'm asking for clarification.

**Comment by ljharb** [comment]
@cscott it was just decided 40 minutes ago. No need to ask, I'm in the room on the committee :-)

**Comment by ljharb** [comment]
Removal from the spec is [here](https://github.com/tc39/ecma262/pull/211)
