### ISSUE TITLE
sticky flag polyfill

### ISSUE THREAD

**Issue by Yaffle** [paulmillr/es6-shim#376]
```
(function (global) {
  var OriginalRegExp = global.RegExp;
  if (!("sticky" in OriginalRegExp.prototype)) {
    var originalExec = OriginalRegExp.prototype.exec;
    OriginalRegExp.prototype.exec = function (string) {
      var lastIndex = this.lastIndex;
      var result = originalExec.call(this, string);
      if (this.sticky && result != null && this.lastIndex - result[0].length !== lastIndex) {
        this.lastIndex = 0;
        return null;
      }
      return result;
    };
    global.RegExp = function (pattern, flags) {
      var i = flags != undefined ? flags.indexOf("y") : -1;
      var x = new OriginalRegExp(pattern, i === -1 ? flags : flags.slice(0, i) + flags.slice(i + 1) + (flags.indexOf("g") === -1 ? "g" : ""));
      x.sticky = i !== -1;
      return x;
    };
  }
}(this));
```

**Comment by Yaffle** [comment]
This does not fix issues String#match, String#search, String#split, String#replace...
But 1) it should be strange to use those methods with sticky flags; 2) if you fix RegExp[@@match] and other methods to call `RegExp#exec` as per specification thouse methods will be fixed automatically...

**Comment by Yaffle** [comment]
4) From my understanding of the specification both Firefox and Chrome works incorrectly for the next edge cases:

console.log( 
 "_foo".match(function (e, i) { e.lastIndex = i; return e; }(/foo/y, 1)),
 "_foo".split(function (e, i) { e.lastIndex = i; return e; }(/foo/y, 1)),
 "_foo".split(function (e, i) { e.lastIndex = i; return e; }(/foo/gy, 1)),
 "_foo".replace(function (e, i) { e.lastIndex = i; return e; }(/foo/y, 1), "?")
);

Am I mistake?

**Comment by ljharb** [comment]
All of the Symbol methods do need to work with the sticky flags. I haven't finished implementing the full semantics of the symbol methods, as you point out - I will soon.

Polyfilling `sticky` by a `_sticky` method isn't something that I'd find acceptable. However, those last test cases - in an environment that natively supports the `y` flag - do seem legitimate. Can you file those as a separate issue?

**Comment by Yaffle** [comment]
> Polyfilling sticky by a _sticky method isn't something that I'd find acceptable.

@ljharb , I am replacing the constructor with custom one, which adds "_sticky" property - a very bad code, but it is simple and you are doing it too already, am i right?
And I am replacing `RegExp#exec` ... which is not bad.

**Comment by ljharb** [comment]
I'm not talking about wrapping the constructor or replacing the methods - I'm not OK with adding publicly visible properties if they can be avoided. Since the sticky flag can't be polyfilled in native syntax, I don't think it'd be worth it.

**Comment by Yaffle** [comment]
@ljharb some compilers convert `/xxx/y` to `new RegExp("xxx", "y")` for those like you

**Comment by Yaffle** [comment]
Edge 13:
```
"foo".match(function (e, i) { e.lastIndex = i; return e; }(/foo/y, 1))
is ["foo"] in Firefox/Chrome, null in Edge 13

"_foo".match(function (e, i) { e.lastIndex = i; return e; }(/foo/y, 1))
is null in Firefox/Chrome, ["foo"] in Edge 13

"foo".replace(function (e, i) { e.lastIndex = i; return e; }(/foo/y, 1), "?")
is "?" in Firefox/Chrome, "foo" in Edge 13

"_foo".replace(function (e, i) { e.lastIndex = i; return e; }(/foo/y, 1), "?")
is "_foo" in Firefox/Chrome, "_?" in Edge 13

"foo".split(function (e, i) { e.lastIndex = i; return e; }(/foo/y, 1))
is ["", ""] in Firefox/Chrome/Edge 13

"_foo".split(function (e, i) { e.lastIndex = i; return e; }(/foo/y, 1))
is ["_foo"] in Firefox/Chrome, ["_",""] in Edge 13

(seems, some methods in Firefox/Chrome work like with "lastIndex == 0" and applied "sticky" flag)
```

**Comment by hax** [comment]
Any update to support sticky?

**Comment by ljharb** [comment]
@hax I'm still willing to consider it, but the effort to only partially support a regex flag doesn't seem worth it to me.

**Comment by Yaffle** [comment]
A new version:
```javascript
var OriginalRegExp = globalThis.RegExp;
if (!('sticky' in OriginalRegExp.prototype)) {
  globalThis.RegExp = function (pattern, flags) {
    'use strict';
    if (flags.replace(/[yi]/g, '') !== '') {
      return new OriginalRegExp(pattern, flags);
    }
    this.lastIndex = 0;
    this.pattern = new OriginalRegExp('^(?:' + new OriginalRegExp(pattern).source + ')', flags.replace(/y/g, 'g'));
    this.exec = function (string) {
      this.pattern.lastIndex = 0;
      var result = OriginalRegExp.prototype.exec.call(this.pattern, string.slice(this.lastIndex));
      this.lastIndex += this.pattern.lastIndex;
      return result;
    };
    this.test = function (string) {
      this.pattern.lastIndex = 0;
      var result = OriginalRegExp.prototype.test.call(this.pattern, string.slice(this.lastIndex));
      this.lastIndex += this.pattern.lastIndex;
      return result;
    };
    return this;
  };
  globalThis.RegExp.prototype = OriginalRegExp.prototype;
}
```

Usage:
```javascript
var re = new RegExp('test', 'y');
re.lastIndex = 1;
console.log(re.exec('a test'));
```
