### ISSUE TITLE
Safari <=9, different behaviour with `(new Function()).name`

### ISSUE THREAD

**Issue by Xotic750** [paulmillr/es6-shim#390]
In Safari 9 I notice that it behaves differently to all other environments I have tested so far.
```
var f = new Function();
alert(f.name);
```
https://jsfiddle.net/Xotic750/mqabqdm0/
On Safari this alerts `'anonymous'`, but everywhere else I have tested it alerts `''`
https://saucelabs.com/beta/tests/e755ffaa8c744824b288d2ec6b6b0366/watch

**Comment by cscott** [comment]
That's a Safari bug, then, and not much es6-shim can do about it.

node/v8 has a similar version of the bug -- the ES6 says that `f.hasOwnProperty('name')` should return `false` if `f` is an anonymous function.  But in the latest node, `f.name` is an own property, with the value ''.  (`Function.prototype.name = ''` so the *value* is right, it just should be inherited from the prototype, not be an own property.)

Anyway, I don't think there's anything we can do about it -- everyone seems to correctly implement `f.name` as not writable, so we can't fix it.

**Comment by Xotic750** [comment]
Thanks. There seem to be quite a few non-fixable bugs within ES6. At least it is documented. ;)

**Comment by cscott** [comment]
Said differently -- "JavaScript engines have a ways to go before they faithfully implement all of ES6."

**Comment by Xotic750** [comment]
I don't know if there is a bug report with Safari for this, actually not even sure where to look.

**Comment by Xotic750** [comment]
I tried submitting a bug via their Bug Reporter, but my pointer just spins and spins and spins. :/

**Comment by ljharb** [comment]
I'm going to close this since function name stuff is unshimmable.

**Comment by JakeChampion** [comment]
I was looking into how we could polyfill `Function.prototype.name` and have come across a [partial implementation](https://github.com/JamesMGreene/Function.name/blob/master/Function.name.js) -- 
```
var fnNamePrefixRegex = /^[\S\s]*?function\s*/;
var fnNameSuffixRegex = /[\s\(\/][\S\s]+$/;

Object.defineProperty(Function.prototype, "name", {
    get: name
});

function name() {
  var name = "";
  if (this === Function || this === Function.prototype.constructor) {
    name = "Function";
  }
  else if (this !== Function.prototype) {
    name = ("" + this).replace(fnNamePrefixRegex, "").replace(fnNameSuffixRegex, "");
  }
  return name;
}
```

@ljharb By unshimmable do you mean it is not feasible or do you mean impossible?

**Comment by ljharb** [comment]
@JakeChampion impossible. The property is nonconfigurable in everything but IE. However, in IE 9 - 11, you could probably add that getter, but I suspect there would be many edge cases, including "native code" functions.
