### ISSUE TITLE
One more time: Number constructor wrapper still removes Number constants in ES3 environment

### ISSUE THREAD

**Issue by zloirock** [paulmillr/es6-shim#402]
After #365 `Object.getOwnPropertyNames` for ES3 environment was changed to `Object.keys`. But `Number` constants are non-enumerable. IE8, last `es5-shim`, `es5-sham`, `es6-shim`:
![default](https://cloud.githubusercontent.com/assets/2213682/12605500/d2886530-c4ef-11e5-974f-b6ed98a607fc.png)
How many times should I report it and to show examples? :)

**Comment by ljharb** [comment]
Thanks, it's hard to deal with multiple problems reported in the same issue, or as comments on github commits - one issue per problem makes it far more likely it will be handled.
