### ISSUE TITLE
Uncaught TypeError: RegExp.prototype.global getter called on non-RegExp object

### ISSUE THREAD

**Issue by b-rucel** [paulmillr/es6-shim#406]
![screen shot 2016-02-09 at 2 28 56 am](https://cloud.githubusercontent.com/assets/150024/12913705/2e03d9e6-ced5-11e5-84ad-1c111ac3c344.png)

**Comment by ljharb** [comment]
@b-rucel are you perhaps using an older version of `es6-shim`, and Chrome Canary?

If you upgrade to the latest version of es6-shim this problem should go away. Note that when using Canary, you should expect lots of things to break often.

**Comment by b-rucel** [comment]
Yeah I should have checked my es6-shim version first. It was one of those late night mistakes, thanks for following up quickly.

**Comment by ljharb** [comment]
np, thanks for the report!
