### ISSUE TITLE
`Array.from` should not touch Array.prototype setters (createDataPropertyOrThrow)

### ISSUE THREAD

**Issue by Yaffle** [paulmillr/es6-shim#415]
An edge case... 

```
Object.defineProperty(Object.prototype, "0", {
  set: function () {
    throw new Error();
  },
  get: function () {
    return undefined;
  }
});

Array.from({length: 1}); // should not throw here

```

**Comment by Yaffle** [comment]
Ah... this was fixed in https://github.com/mathiasbynens/Array.from ... sorry

**Comment by ljharb** [comment]
Hmm, there's no fix for this in https://github.com/mathiasbynens/Array.from or this repo at all?

However, according to https://tc39.github.io/ecma262/#sec-array.from step 12.b., it seems like it should indeed throw in this case.

**Comment by Yaffle** [comment]
What about step 12.e ?

**Comment by ljharb** [comment]
Ah, you're correct that step 12e is what applies here - but the `?` in the spec means if CreateDataPropertyOrThrow returns an abrupt completion, that the exception should be thrown.

**Comment by Yaffle** [comment]
OK

**Comment by Yaffle** [comment]
@ljharb The setter will not be touched with `CreateDataPropertyOrThrow`.

**Comment by ljharb** [comment]
Good call, you're totally correct. Thanks for clarifying.
