### ISSUE TITLE
Array.prototype.includes is missing

### ISSUE THREAD

**Issue by GaryB432** [paulmillr/es6-shim#416]
I was wondering if this was an oversight or am I misunderstanding your repo.  The method does seem to be part of [the spec](https://tc39.github.io/ecma262/2016/#sec-array.prototype.includes).

I'm using node v4.4.1 and `Array.prototype.includes` is undefined as might be expected so I was thinking about using this shim.

Thanks for the great repo!

**Comment by ljharb** [comment]
This is part of ES7/ES2016, not ES6. It doesn't belong in this shim.

I recommend using http://npmjs.com/array-includes to shim it.
