### ISSUE TITLE
Add Array.prototype.includes

### ISSUE THREAD

**Issue by saghul** [paulmillr/es6-shim#417]
It would be a nice to have.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

**Comment by ljharb** [comment]
It's part of ES7/ES2016, not ES6/ES2015.

I recommend https://www.npmjs.com/package/array-includes.

**Comment by saghul** [comment]
Ops, thanks for the pointer!
