### ISSUE TITLE
Object.isExtensible (and likely others) return incorrect result for functions

### ISSUE THREAD

**Issue by whyisthisfieldhere** [paulmillr/es6-shim#418]
According to both (my understanding of) the ES6 spec and firefox, Object.isExtensible should return true for functions (as they are considered object types)
However, es6-shim's Object.isExtensible returns false for functions because it uses Type.object instead of !Type.primitive for checking the argument.
As a practical example, this bug breaks Benvie's WeakMap shim when applied to functions.

I've just checked and the other usages of Type.object (seal, isSealed, freeze, isFrozed,preventExtensions) have the same issue according to MUO of the spec.

(Sidenote - why not add something like Benvie's WeakMap shim as a shim or sham? it seems well good enough)

**Comment by ljharb** [comment]
Thanks! Let me fix that right now.

**Comment by ljharb** [comment]
Released as v0.35.1.
