### ISSUE TITLE
Set missing forEach method on Firefox 24

### ISSUE THREAD

**Issue by mockdeep** [paulmillr/es6-shim#421]
Looks similar to https://github.com/paulmillr/es6-shim/issues/143, but using Lodash on Firefox 24 results in an error: `TypeError: set.forEach is not a function`. Looks like `Set` is defined, but doesn't implement `forEach`.

**Comment by ljharb** [comment]
Can you make a jsfiddle that reproduces the issue?

**Comment by mockdeep** [comment]
Sure, there's not much to it: https://jsfiddle.net/dgswvqc7/

**Comment by ljharb** [comment]
Ideally one that includes es6-shim :-)

**Comment by mockdeep** [comment]
Hmm, it seems to [work with the jsfiddle](https://jsfiddle.net/dgswvqc7/1/), so I guess it must be on my end. Let me verify that the shims are included properly.

**Comment by mockdeep** [comment]
Doh! Turns out I had included `es6-sham` instead of `es6-shim`. It's all working now.

**Comment by ljharb** [comment]
es6-sham requires es6-shim first be included. Glad you figured it out and thanks for the followup!
