### ISSUE TITLE
set/get ngFor performance on IE11

### ISSUE THREAD

**Issue by aronallen** [paulmillr/es6-shim#422]
Hi,

We are having this issue in Angular 2 land.
Any chance shim performance can be improved for IE11.

https://github.com/angular/angular/issues/8112

> The code is constantly calling isNan function in es6-shim.js.
> The problem seems to be due to the reason that set and get functions of the polyfill are extremely slow (compared to their native counterparts) and take most of the time.

**Comment by ljharb** [comment]
I'd be happy to improve performance wherever it can be done without sacrificing correctness.

I'm not sure what the best way to do that is, but am open to PRs.

**Comment by jdalton** [comment]
I'll give a PR a try :grinning:

**Comment by ljharb** [comment]
@aronallen #429 is released with [v0.35.2](https://github.com/paulmillr/es6-shim/releases/tag/v0.35.2) - please let me know if that does not resolve your performance issue.
