### ISSUE TITLE
Typing for Promise#catch

### ISSUE THREAD

**Issue by rtm** [paulmillr/es6-shim#423]
Is there any reason for this overload in the typings file?
The preceding line would seem to encompass this one.

    catch(onrejected?: (reason: any) => T | PromiseLike<T> | void): Promise<T>;

**Comment by ljharb** [comment]
What typings file are you referring to?

**Comment by rtm** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/es6-shim/es6-shim.d.ts

**Comment by ljharb** [comment]
That's not this repo, so I'm not sure what you want me to do about it.

It looks like the SO answer explains the problem with trying to statically type non-statically-typable interfaces.
