### ISSUE TITLE
Tweak documentation to specify inclusion order of es5-shim and es6-shim

### ISSUE THREAD

**Issue by jibesh** [paulmillr/es6-shim#434]
For using in the browser, the documentation says '_it's strongly recommended to always include es5-shim_' but it does not specify the order of inclusion. A side effect of not doing so is as follows:
  - Only using es6-shim, the identifier returnExports points to an Object.
  - If es5-shim is included before es6-shim, the identifier returnExports still points to an Object.
  - But if es5-shim is included after es6-shim, returnExports becomes undefined.
  As a result, I would like to suggest a tweak in the documentation that specifies an inclusion order.

**Comment by ljharb** [comment]
Very good point, a PR would be welcome.

(That said, nobody should be using `returnExports`, because it's a shim - it's meant to simply install things on the environment)
