### ISSUE TITLE
How to use es6-shim with modernizr in IE 11.

### ISSUE THREAD

**Issue by wiadev** [paulmillr/es6-shim#443]
Hi
I'm trying to build a web app with object.assign but it's not supported on IE 11.
So I've included modernizr and going to use es6-shim but not sure how to use them on my problem.
I'm not using npm, bower, etc but include all js files in my project /lib folder.

Thanks.

**Comment by ljharb** [comment]
Simply importing/requiring `es6-shim` at the top of your project - before modernizr - should provide `Object.assign`.
