### ISSUE TITLE
Installed es6-shim types reference type "object", rather than "Object"?

### ISSUE THREAD

**Issue by dtgriscom** [paulmillr/es6-shim#445]
In using TypeScript and TypeDoc, I was having trouble with tsc errors on undefined Promise types. So, after some Googling, I installed es6-shim:

```
npm install --save @types/es6-shim
```
Now, tsc complains that it can't find name `object`:
```
tsc --project fpui --watch
node_modules/@types/es6-shim/index.d.ts(596,29): error TS2304: Cannot find name 'object'.
node_modules/@types/es6-shim/index.d.ts(604,20): error TS2304: Cannot find name 'object'.
node_modules/@types/es6-shim/index.d.ts(605,20): error TS2304: Cannot find name 'object'.
1:55:04 PM - Compilation complete. Watching for file changes.
```
Looking at the cited lines, I find that the WeakMap type's argument refer to the type `object`, instead of what I would assume should be `Object`:
```
interface WeakMap<K extends object, V> {
    delete(key: K): boolean;
    get(key: K): V | undefined;
    has(key: K): boolean;
    set(key: K, value: V): WeakMap<K, V>;
}

interface WeakMapConstructor {
    new <K extends object, V>(): WeakMap<K, V>;
    new <K extends object, V>(iterable: IterableShim<[K, V]>): WeakMap<K, V>;
    prototype: WeakMap<any, any>;
}
```

I'm using tsc version 2.0.10, and npm version 3.10.10.

Any suggestions?

**Comment by ljharb** [comment]
This project doesn't use typescript, and we don't support or maintain the TypeScript definitions for it.

Please file an issue on the DefinitelyTyped repo instead.

**Comment by dtgriscom** [comment]
Thanks,
Dan
