### ISSUE TITLE
Zip package for v0.35.2 and v0.35.3, es6-shim.js comment block indicates 0.35.1

### ISSUE THREAD

**Issue by JimInWA** [paulmillr/es6-shim#447]
Looked here and at https://github.com/es-shims/es6-shim/releases, same issue.

Note: I realize that this is a minor issue, just documenting it so other people are aware.

- Go to the Releases and download the source code zip file for v0.35.2
- Open the es6-shim.js file
- Comment block indicates 0.35.1

Same issue for v0.35.3 zip file

**Comment by ljharb** [comment]
This was fixed in 61b9685dc47a3adcd6eadf5935c6921435538ee4 / https://github.com/paulmillr/es6-shim/commit/129819173958a0da2b487e219425baf0ca6d1a99#commitcomment-20827458.
