### ISSUE TITLE
Support for Promise.prototype.finally

### ISSUE THREAD

**Issue by nmoinvaz** [paulmillr/es6-shim#450]
It appears that Promise.prototype.finally has been accepted. 
https://github.com/tc39/proposals/blob/master/finished-proposals.md
It would be great to have this included in this ES6 shim.

**Comment by ljharb** [comment]
Promise.prototype.finally is part of ES2018 - this shim is exclusively and only for ES2015.

The official shim for finally is https://npmjs.com/promise.prototype.finally, which is also included in https://npmjs.com/airbnb-browser-shims.

**Comment by nmoinvaz** [comment]
Thanks!
