### ISSUE TITLE
Question: Template literals supported?

### ISSUE THREAD

**Issue by GitToTheHub** [paulmillr/es6-shim#452]
I only wanted to ask, if template literals are supported, like this:

```
var myVar = "test";
console.log(`This is a ${myVar}`);
```

Thank for responding :)

**Comment by zloirock** [comment]
It can't be polyfilled, it's a work for transpiler. For modern syntax support, use Babel.

**Comment by GitToTheHub** [comment]
Ok, thank you for your reply!
Can i maybe use this syntax style:
```
var myString = "This is a very long string which needs \
to wrap across multiple lines because \
otherwise my code is unreadable.";
```

**Comment by ljharb** [comment]
That’s alwsys been part of JS, but yes.

In general, syntax must be transpiled; only API can be polyfilled.

**Comment by GitToTheHub** [comment]
Ok, thank you really much for your reply :)
Have a nice day :)
