### ISSUE TITLE
Possible to only use needed components?

### ISSUE THREAD

**Issue by notflip** [paulmillr/es6-shim#453]
Is it possible to not include the complete library, and only use the shims I need for a project?

**Comment by ljharb** [comment]
How can you know that? You don’t know what shims all of your dependencies need.

Some of these do have standalone shims, but not all. In general tho, it’s a best practice to always unconditionally shim everything.

**Comment by zloirock** [comment]
If you need it, you can use [`core-js`](https://github.com/zloirock/core-js).
