### ISSUE TITLE
Unneeded argument for overrideNative

### ISSUE THREAD

**Issue by lukastaegert** [paulmillr/es6-shim#456]
Here and in the following lines, Rollup considers the final argument `true` to `overrideNative` to be superfluous, to which I agree looking at the definition.

https://github.com/paulmillr/es6-shim/blob/b5cca2ad271a7f9c80a7bfea4d05f875c80dd400/es6-shim.js#L1319

https://github.com/paulmillr/es6-shim/blob/b5cca2ad271a7f9c80a7bfea4d05f875c80dd400/es6-shim.js#L267

Is this correct?

**Comment by ljharb** [comment]
Indeed you're right, I'm not sure why those pass a 4th argument.

**Comment by ljharb** [comment]
Fixed in 276c60c.
