### ISSUE TITLE
Does the array `of` shim apply to `for...of`?

### ISSUE THREAD

**Issue by johnaweiss** [paulmillr/es6-shim#463]
for example

`for(var c of "tree 木") { console.log(c); }`

Thanks

**Comment by ljharb** [comment]
In any environment where `for..of` respects a native `Symbol.iterator` (or similar), this shim will cover it.

There may be an environment or three where `for..of` only works on, for example, Maps and Sets, and there's no native Symbols - but it's impossible to do anything about those.

Do you have specific environments in mind?

**Comment by johnaweiss** [comment]
just general cross-browser web-development.

**Comment by ljharb** [comment]
Yes, that would include that code.

I'm pretty confident you'll be fine; please file an issue with specific details if you find a browser where it doesn't work. (of course, you should be using babel to transpile, which will handle `for..of` syntax properly)
