### ISSUE TITLE
Promise shim missing finally method

### ISSUE THREAD

**Issue by darxis** [paulmillr/es6-shim#472]
I am using `es6-shim` on some old Android device and I am experiencing errors when trying to call Promise.finally: 
>  Object #<Promise> has no method 'finally'

The following code outputs `catch,then,constructor` on my old Android device and outputs `catch,then,finally,constructor` on a modern PC browser.

```
let promise = ...;
alert(Object.getOwnPropertyNames(Object.getPrototypeOf(promise)).join(','));
```

It seems that `Promise.finally` has not been implemented yet?

**Comment by ljharb** [comment]
It's not missing - the method isn't in ES6, it was added in ES2018.

Use https://www.npmjs.com/package/promise.prototype.finally to shim it, *on top of* the es6-shim.
