### ISSUE TITLE
 This software has new code recently, but no new version has been released. Will there be a new version released recently?

### ISSUE THREAD

**Issue by chemsky** [paulmillr/es6-shim#475]
This software has new code recently, but no new version has been released. Will there be a new version released recently?

**Comment by ljharb** [comment]
There has been precisely one commit that affects the production code since the last release: https://github.com/paulmillr/es6-shim/compare/0.35.6...master are you waiting for the WSH fix?

**Comment by chemsky** [comment]
no.
It's only been a long time since the last version 0.35.6 was released. I want to confirm whether there is a new version released recently. thank you.

**Comment by ljharb** [comment]
Time since a last release is never inherently important for any package. There is a change waiting, so I could make a release, but it hasn't been urgent.

**Comment by juranjun** [comment]
Could you update a new release please, we also need new release for es6-shim in our front-end code, This software is very useful for us, our commiter expects a newer release version of es6-shim (the update time of the last version is too long from now, 2 years ago), so we expect you to upgrade a new version if possible, thank u.
