### ISSUE TITLE
Documentation Icon Errors and typos

### ISSUE THREAD

**Issue by 0xSaksham** [paulmillr/es6-shim#478]
1. [x] There are some typos in the Readme. md file that I have fixed in my fork. 

2. [ ] Under [this](https://github.com/paulmillr/es6-shim#es6-shim) heading the icons and information are not loading. 

Just lead me to the resources for task 2 and it will be done.

**Comment by ljharb** [comment]
Fixed the latter in 29b67d8b383fec764fd6633b3df1a713626d7e94. For the former, feel free to file a PR here (not against the es-shims fork)
